import 'bootstrap/dist/css/bootstrap.css';

export const metadata = {
    title: 'Dating-company',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css"
                />
            </head>
            <body>{children}</body>
        </html>
    );
}
